#!/usr/bin/env zsh
# The Primogen "ubuntu"
if [[ -z $STOW_FOLDERS ]]; then
    STOW_FOLDERS="alacritty,autostart,bin,git,plank,tmux,ulauncher,nvim,zsh"
fi

if [[ -z $DOTFILES ]]; then
    DOTFILES=$HOME/.dotfiles
fi

# ThePrimogen "install"
pushd $DOTFILES
for folder in $(echo $STOW_FOLDERS | sed "s/,/ /g")
do
    stow -D $folder
    stow $folder
done
popd
