#!/bin/sh

location=/
[ -d "$location" ] || exit
icon=" "
# 1             2       3       4       5
# Filesystem    Size    Used    Avail   Use%
echo "$icon $(df -h "$location" | awk ' /[0-9]/ {print $4}')"
