local settings = {
    icons = {
        diagnostics = {
            error = ' ',
            warn = ' ',
            hint = ' ',
            info = ' ',
        },
        git = {
            added = ' ',
            modified = '柳',
            removed = ' ',
        },
        navic = {
            Array = ' ',
            Boolean = ' ',
            Class = ' ',
            Constant = ' ',
            Constructor = ' ',
            Enum = ' ',
            EnumMember = ' ',
            Event = ' ',
            Field = ' ',
            File = ' ',
            Function = ' ',
            Interface = ' ',
            Key = ' ',
            Method = ' ',
            Module = ' ',
            Namespace = ' ',
            Null = ' ',
            Number = ' ',
            Object = ' ',
            Operator = ' ',
            Package = ' ',
            Property = ' ',
            String = ' ',
            Struct = ' ',
            TypeParameter = ' ',
            Variable = ' ',
        },
    },
}

return settings
